### ISSUE TITLE
Type net.sqlcipher.AbstractCursor$SelfContentObserver is defined multiple times

### ISSUE THREAD

**Issue by darkedges** [jepiqueau/capacitor-data-storage-sqlite#20]
Not sure whethere is this modules issue or something else.
Not sure where the second instance is coming from.

using Ionc 5 framework and followed the instruction in the README

```bash
> Task :app:mergeExtDexDebug
C:\Users\NIrving\.gradle\caches\transforms-2\files-2.1\1faa43fcc1f5807d8a75f529c4f27585\jetified-android-database-sqlcipher-4.3.0-runtime\classes.dex: D8: Type net.sqlcipher.AbstractCursor$SelfContentObserver is defined multiple times: C:\Users\NIrving\.gradle\caches\transforms-2\files-2.1\1faa43fcc1f5807d8a75f529c4f27585\jetified-android-database-sqlcipher-4.3.0-runtime\classes.dex, C:\development\ionic\capApp\android\app\build\intermediates\external_file_lib_dex_archives\debug\out\0_jetified-android-database-sqlcipher-classes.jar:classes.dex
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type net.sqlcipher.AbstractCursor$SelfContentObserver is defined multiple times: C:\Users\NIrving\.gradle\caches\transforms-2\files-2.1\1faa43fcc1f5807d8a75f529c4f27585\jetified-android-database-sqlcipher-4.3.0-runtime\classes.dex, C:\development\ionic\capApp\android\app\build\intermediates\external_file_lib_dex_archives\debug\out\0_jetified-android-database-sqlcipher-classes.jar:classes.dex
        at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:132)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:119)
        at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
        at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:445)
        at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:348)
        at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
        at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
        at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.O.a(:65)
        at com.android.tools.r8.D8.run(:11)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:117)
        ... 34 more
```

**Comment by darkedges** [comment]
By adding  `multiDexEnabled true` to `build.gradle` within `android \ defaultConfig` I was able to bypass this error. Could not find out why there was a duplicate class though.

**Comment by jepiqueau** [comment]
@darkedges Hi, first thanks for using this plugin, Can you tell me more about the context in which this happening. Is it when you where doing encryption of the store or is it when you are get, keys, values or keyvalues methods ?

**Comment by darkedges** [comment]
Seemed to have cleaned it up by doing a `gradle clean` without adding `multiDexEnabled true`. Can close this as Developer error.
